/**
 * Minimal "charger" service — bridges the thin Worker to the Node-only
 * X402ArciumClient. M5 DRAFT, UNVERIFIED example skeleton (not deploy-wired).
 *
 * The Worker (gateway/src/lib/arcium.ts real path) POSTs { agent, price } here;
 * this process runs the real Arcium charge off the hot path and returns the
 * boolean. Run with a Node Solana env (ANCHOR_PROVIDER_URL, ANCHOR_WALLET) once
 * the program is built (M3) and deployed (M4).
 */

import http from "http";
import * as anchor from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";
import { X402ArciumClient } from "./x402-arcium-client";
// Generated by `anchor build` (M3) — will not resolve until then.
import type { X402Gateway } from "../target/types/x402_gateway";

async function main() {
  // Reads ANCHOR_PROVIDER_URL + ANCHOR_WALLET from the environment.
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.X402Gateway as anchor.Program<X402Gateway>;

  const client = new X402ArciumClient(provider, program, provider.wallet.payer!);
  await client.init();

  const server = http.createServer((req, res) => {
    if (req.method !== "POST" || req.url !== "/charge") {
      res.writeHead(404).end();
      return;
    }
    let raw = "";
    req.on("data", (c) => (raw += c));
    req.on("end", async () => {
      try {
        const { agent, price } = JSON.parse(raw) as { agent: string; price: number };
        const { paidOk, finalizeSig } = await client.charge(
          new PublicKey(agent),
          BigInt(price),
        );
        res.writeHead(200, { "content-type": "application/json" });
        res.end(JSON.stringify({ paid_ok: paidOk, computationId: finalizeSig }));
      } catch (err) {
        res.writeHead(500, { "content-type": "application/json" });
        res.end(JSON.stringify({ error: String(err) }));
      }
    });
  });

  const port = Number(process.env.PORT ?? 8788);
  server.listen(port, () => console.log(`charger listening on :${port}`));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
