/**
 * x402 Private Gateway — Arcium client module (Node side, off the hot path).
 *
 * ┌─ STATUS: M5 DRAFT — UNVERIFIED ───────────────────────────────────────────┐
 * │ Ported verbatim from arcium-mxe/tests/x402_gateway.ts (which itself is     │
 * │ written from arcium-hq/examples). It has NOT been run: it depends on the   │
 * │ compiled program id + generated IDL types (`X402Gateway`) that only exist  │
 * │ after `arcium build` (M3) and a devnet deploy (M4). Treat method names and │
 * │ account wiring as provisional until then.                                  │
 * └────────────────────────────────────────────────────────────────────────────┘
 *
 * Why this is a separate module (not inside gateway/src/lib/arcium.ts):
 *   • `@coral-xyz/anchor` + `@arcium-hq/client` need Node (websockets/event
 *     listeners, fs), which do not run inside a Cloudflare Worker.
 *   • M0-② decision = verification OFF the hot path. The real encrypt→queue→
 *     finalize→decrypt round-trips happen here, in a Node process; the Worker
 *     stays a thin layer that delegates (see gateway/src/lib/arcium.ts) and only
 *     consumes the cheap boolean result.
 *
 * Flow per call mirrors the test: getMXEPublicKey → x25519 shared secret →
 * RescueCipher.encrypt(amount, nonce) → queue the Anchor ix → awaitComputation-
 * Finalization → read the emitted event (paid_ok / revealed balance).
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair } from "@solana/web3.js";
import { randomBytes, createHash } from "crypto";
import nacl from "tweetnacl";
import {
  awaitComputationFinalization,
  getArciumEnv,
  getCompDefAccOffset,
  RescueCipher,
  deserializeLE,
  getMXEAccAddress,
  getMempoolAccAddress,
  getCompDefAccAddress,
  getExecutingPoolAccAddress,
  x25519,
  getComputationAccAddress,
  getMXEPublicKey,
  getClusterAccAddress,
} from "@arcium-hq/client";

// Generated by `anchor build` (M3). Until then this import will not resolve —
// that is expected for the draft.
import type { X402Gateway } from "../target/types/x402_gateway";

const ENCRYPTION_KEY_MESSAGE = "x402-gateway-encryption-key-v1";

/** Derive a deterministic X25519 keypair from a Solana wallet (写経: test). */
function deriveEncryptionKey(
  wallet: Keypair,
  message: string
): { privateKey: Uint8Array; publicKey: Uint8Array } {
  const messageBytes = new TextEncoder().encode(message);
  const signature = nacl.sign.detached(messageBytes, wallet.secretKey);
  const privateKey = new Uint8Array(
    createHash("sha256").update(signature).digest()
  );
  const publicKey = x25519.getPublicKey(privateKey);
  return { privateKey, publicKey };
}

async function getMXEPublicKeyWithRetry(
  provider: anchor.AnchorProvider,
  programId: PublicKey,
  maxRetries = 20,
  retryDelayMs = 500
): Promise<Uint8Array> {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const k = await getMXEPublicKey(provider, programId);
      if (k) return k;
    } catch {
      /* retry */
    }
    if (attempt < maxRetries) {
      await new Promise((r) => setTimeout(r, retryDelayMs));
    }
  }
  throw new Error(`Failed to fetch MXE public key after ${maxRetries} attempts`);
}

export interface ChargeResult {
  paidOk: boolean;
  finalizeSig: string;
}

/**
 * Encapsulates all Arcium round-trips for one agent's prepaid balance.
 * Construct, `await init()`, then call open/deposit/charge/revealBalance.
 */
export class X402ArciumClient {
  private cipher!: RescueCipher;
  private encryptionPubkey!: Uint8Array;
  private readonly arciumEnv = getArciumEnv();
  private readonly clusterAccount = getClusterAccAddress(
    this.arciumEnv.arciumClusterOffset
  );

  constructor(
    private readonly provider: anchor.AnchorProvider,
    private readonly program: Program<X402Gateway>,
    private readonly owner: Keypair
  ) {}

  /** Fetch the MXE public key and build the per-agent RescueCipher. */
  async init(): Promise<void> {
    const mxePublicKey = await getMXEPublicKeyWithRetry(
      this.provider,
      this.program.programId
    );
    const { privateKey, publicKey } = deriveEncryptionKey(
      this.owner,
      ENCRYPTION_KEY_MESSAGE
    );
    this.encryptionPubkey = publicKey;
    const sharedSecret = x25519.getSharedSecret(privateKey, mxePublicKey);
    this.cipher = new RescueCipher(sharedSecret);
  }

  private balancePDA(authority: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("balance"), authority.toBuffer()],
      this.program.programId
    )[0];
  }

  private queueAccounts(compDefName: string, offset: anchor.BN) {
    return {
      computationAccount: getComputationAccAddress(
        this.arciumEnv.arciumClusterOffset,
        offset
      ),
      clusterAccount: this.clusterAccount,
      mxeAccount: getMXEAccAddress(this.program.programId),
      mempoolAccount: getMempoolAccAddress(this.arciumEnv.arciumClusterOffset),
      executingPool: getExecutingPoolAccAddress(
        this.arciumEnv.arciumClusterOffset
      ),
      compDefAccount: getCompDefAccAddress(
        this.program.programId,
        Buffer.from(getCompDefAccOffset(compDefName)).readUInt32LE()
      ),
    };
  }

  private async finalize(offset: anchor.BN): Promise<string> {
    return awaitComputationFinalization(
      this.provider,
      offset,
      this.program.programId,
      "confirmed"
    );
  }

  /** Open a zero encrypted balance for `authority` (init_balance). */
  async openBalance(authority: PublicKey): Promise<string> {
    const offset = new anchor.BN(randomBytes(8), "hex");
    await this.program.methods
      .openBalance(offset)
      .accountsPartial({
        authority,
        agentBalance: this.balancePDA(authority),
        ...this.queueAccounts("init_balance", offset),
      })
      .rpc({ skipPreflight: true, commitment: "confirmed" });
    return this.finalize(offset);
  }

  /** Top up the encrypted balance by `amount` base units (deposit). */
  async deposit(authority: PublicKey, amount: bigint): Promise<string> {
    return this.submitAmount("deposit", authority, amount);
  }

  /**
   * Charge `price` base units against the encrypted balance (the 402 gate).
   * Returns `paidOk` read from the emitted ChargeEvent — the only revealed value.
   */
  async charge(authority: PublicKey, price: bigint): Promise<ChargeResult> {
    const eventPromise = this.awaitEvent("chargeEvent");
    const finalizeSig = await this.submitAmount("charge", authority, price);
    const ev = await eventPromise;
    return { paidOk: ev.paidOk as boolean, finalizeSig };
  }

  /** Owner-only: reveal the current balance (reveal_balance). */
  async revealBalance(authority: PublicKey): Promise<bigint> {
    const eventPromise = this.awaitEvent("revealBalanceEvent");
    const offset = new anchor.BN(randomBytes(8), "hex");
    await this.program.methods
      .revealBalance(offset)
      .accountsPartial({
        agentBalance: this.balancePDA(authority),
        ...this.queueAccounts("reveal_balance", offset),
      })
      .rpc({ skipPreflight: true, commitment: "confirmed" });
    await this.finalize(offset);
    const ev = await eventPromise;
    return BigInt(ev.amount.toString());
  }

  /** Encrypt a u64 amount and queue a deposit/charge (写経: test submitAmount). */
  private async submitAmount(
    method: "deposit" | "charge",
    authority: PublicKey,
    amount: bigint
  ): Promise<string> {
    const nonce = randomBytes(16);
    const ciphertext = this.cipher.encrypt([amount], nonce);
    const offset = new anchor.BN(randomBytes(8), "hex");
    const nonceArg = new anchor.BN(deserializeLE(nonce).toString());

    const builder =
      method === "deposit"
        ? this.program.methods.deposit(
            offset,
            Array.from(ciphertext[0]),
            Array.from(this.encryptionPubkey),
            nonceArg
          )
        : this.program.methods.charge(
            offset,
            Array.from(ciphertext[0]),
            Array.from(this.encryptionPubkey),
            nonceArg
          );

    await builder
      .accountsPartial({
        authority,
        agentBalance: this.balancePDA(authority),
        ...this.queueAccounts(method, offset),
      })
      .rpc({ skipPreflight: true, commitment: "confirmed" });

    return this.finalize(offset);
  }

  /** Resolve the next occurrence of an event (写经: test awaitEvent). */
  private awaitEvent(eventName: string, timeoutMs = 120000): Promise<any> {
    let listenerId: number;
    let timeoutId: NodeJS.Timeout;
    return new Promise((res, rej) => {
      listenerId = this.program.addEventListener(eventName as any, (ev) => {
        clearTimeout(timeoutId);
        this.program.removeEventListener(listenerId);
        res(ev);
      });
      timeoutId = setTimeout(() => {
        this.program.removeEventListener(listenerId);
        rej(new Error(`Event ${eventName} timed out after ${timeoutMs}ms`));
      }, timeoutMs);
    });
  }
}
